name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trxviewer:$(date +%s)
    - name: "Extract extension to disk"
      run: mkdir /out && docker run --mount type=bind,source=/out,target=/extract trxviewer:$(date +%s)
    - name: Upload vsix Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: /out/*.vsix
    
